{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "sagemaker.config INFO - Not applying SDK defaults from location: C:\\ProgramData\\sagemaker\\sagemaker\\config.yaml\n",
      "sagemaker.config INFO - Not applying SDK defaults from location: C:\\Users\\Admin\\AppData\\Local\\sagemaker\\sagemaker\\config.yaml\n",
      "Endpoint configuration simple-linear-regression-endpoint-config does not exist. Proceeding to create a new one.\n",
      "Endpoint simple-linear-regression-endpoint does not exist. Proceeding to create a new one.\n"
     ]
    }
   ],
   "source": [
    "# Install necessary libraries\n",
    "# !pip install boto3 sagemaker pandas scikit-learn\n",
    "\n",
    "# Import necessary libraries\n",
    "import boto3\n",
    "import sagemaker\n",
    "from sagemaker import get_execution_role\n",
    "import time\n",
    "\n",
    "# Define parameters\n",
    "role = 'arn:aws:iam::728939754004:role/service-role/AmazonSageMaker-ExecutionRole-20230821T133341'  # Your SageMaker execution role ARN\n",
    "region = 'us-east-1'\n",
    "s3_bucket = 'justin-inferences'  # Your S3 bucket for model artifacts\n",
    "model_artifact_path = f's3://{s3_bucket}/model/model.pkl'\n",
    "endpoint_name = 'simple-linear-regression-endpoint'\n",
    "endpoint_config_name = 'simple-linear-regression-endpoint-config'\n",
    "\n",
    "# Create a SageMaker session\n",
    "sagemaker_session = sagemaker.Session()\n",
    "\n",
    "# Initialize SageMaker client\n",
    "sm_client = boto3.client('sagemaker', region_name=region)\n",
    "\n",
    "# Function to delete existing endpoint configuration\n",
    "def delete_endpoint_config(config_name):\n",
    "    try:\n",
    "        sm_client.describe_endpoint_config(EndpointConfigName=config_name)\n",
    "        print(f\"Endpoint configuration {config_name} already exists. Deleting it...\")\n",
    "        sm_client.delete_endpoint_config(EndpointConfigName=config_name)\n",
    "        print(f\"Deleted endpoint configuration {config_name}.\")\n",
    "    except sm_client.exceptions.ClientError as e:\n",
    "        if 'ValidationException' in str(e):\n",
    "            print(f\"Endpoint configuration {config_name} does not exist. Proceeding to create a new one.\")\n",
    "        else:\n",
    "            raise e\n",
    "\n",
    "# Function to delete existing endpoint\n",
    "def delete_endpoint(endpoint_name):\n",
    "    try:\n",
    "        sm_client.describe_endpoint(EndpointName=endpoint_name)\n",
    "        print(f\"Endpoint {endpoint_name} already exists. Deleting it...\")\n",
    "        sm_client.delete_endpoint(EndpointName=endpoint_name)\n",
    "        print(f\"Deleted endpoint {endpoint_name}.\")\n",
    "        # Wait for the endpoint to be deleted\n",
    "        waiter = sm_client.get_waiter('endpoint_deleted')\n",
    "        waiter.wait(EndpointName=endpoint_name)\n",
    "        print(f\"Endpoint {endpoint_name} deleted.\")\n",
    "    except sm_client.exceptions.ClientError as e:\n",
    "        if 'ValidationException' in str(e):\n",
    "            print(f\"Endpoint {endpoint_name} does not exist. Proceeding to create a new one.\")\n",
    "        else:\n",
    "            raise e\n",
    "\n",
    "# Delete existing endpoint configuration if it exists\n",
    "delete_endpoint_config(endpoint_config_name)\n",
    "\n",
    "# Delete existing endpoint if it exists\n",
    "delete_endpoint(endpoint_name)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Endpoint configuration simple-linear-regression-endpoint-config has been deleted.\n"
     ]
    }
   ],
   "source": [
    "# Ensure endpoint configuration is deleted before proceeding\n",
    "while True:\n",
    "    try:\n",
    "        sm_client.describe_endpoint_config(EndpointConfigName=endpoint_config_name)\n",
    "        print(f\"Waiting for endpoint configuration {endpoint_config_name} to be deleted...\")\n",
    "        time.sleep(10)\n",
    "    except sm_client.exceptions.ClientError as e:\n",
    "        if 'ValidationException' in str(e):\n",
    "            print(f\"Endpoint configuration {endpoint_config_name} has been deleted.\")\n",
    "            break\n",
    "        else:\n",
    "            raise e"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a SageMaker model\n",
    "model = sagemaker.model.Model(\n",
    "    model_data=model_artifact_path,\n",
    "    image_uri=sagemaker.image_uris.retrieve('linear-learner', region),\n",
    "    role=role,\n",
    "    sagemaker_session=sagemaker_session\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "ename": "ClientError",
     "evalue": "An error occurred (ValidationException) when calling the CreateEndpointConfig operation: Cannot create already existing endpoint configuration \"arn:aws:sagemaker:us-east-1:728939754004:endpoint-config/simple-linear-regression-endpoint\".",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mClientError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_39316/3658508801.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;31m# Deploy the model to an endpoint\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m predictor = model.deploy(\n\u001b[0m\u001b[0;32m      3\u001b[0m     \u001b[0minitial_instance_count\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m     \u001b[0minstance_type\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'ml.m5.large'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m     \u001b[0mendpoint_name\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mendpoint_name\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\Admin\\anaconda3\\envs\\tf-gpu-cuda8\\lib\\site-packages\\sagemaker\\model.py\u001b[0m in \u001b[0;36mdeploy\u001b[1;34m(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, tags, kms_key, wait, data_capture_config, async_inference_config, serverless_inference_config, volume_size, model_data_download_timeout, container_startup_health_check_timeout, inference_recommendation_id, explainer_config, accept_eula, **kwargs)\u001b[0m\n\u001b[0;32m   1503\u001b[0m             \u001b[0mexplainer_config_dict\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mexplainer_config\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_to_request_dict\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1504\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1505\u001b[1;33m         self.sagemaker_session.endpoint_from_production_variants(\n\u001b[0m\u001b[0;32m   1506\u001b[0m             \u001b[0mname\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mendpoint_name\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1507\u001b[0m             \u001b[0mproduction_variants\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mproduction_variant\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\Admin\\anaconda3\\envs\\tf-gpu-cuda8\\lib\\site-packages\\sagemaker\\session.py\u001b[0m in \u001b[0;36mendpoint_from_production_variants\u001b[1;34m(self, name, production_variants, tags, kms_key, wait, data_capture_config_dict, async_inference_config_dict, explainer_config_dict)\u001b[0m\n\u001b[0;32m   4847\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   4848\u001b[0m         \u001b[0mLOGGER\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0minfo\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Creating endpoint-config with name %s\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mname\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 4849\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msagemaker_client\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcreate_endpoint_config\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m**\u001b[0m\u001b[0mconfig_options\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   4850\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   4851\u001b[0m         return self.create_endpoint(\n",
      "\u001b[1;32mc:\\Users\\Admin\\anaconda3\\envs\\tf-gpu-cuda8\\lib\\site-packages\\botocore\\client.py\u001b[0m in \u001b[0;36m_api_call\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    533\u001b[0m                 )\n\u001b[0;32m    534\u001b[0m             \u001b[1;31m# The \"self\" in this scope is referring to the BaseClient.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 535\u001b[1;33m             \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_make_api_call\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0moperation_name\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    536\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    537\u001b[0m         \u001b[0m_api_call\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__name__\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mstr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpy_operation_name\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\Admin\\anaconda3\\envs\\tf-gpu-cuda8\\lib\\site-packages\\botocore\\client.py\u001b[0m in \u001b[0;36m_make_api_call\u001b[1;34m(self, operation_name, api_params)\u001b[0m\n\u001b[0;32m    981\u001b[0m             )\n\u001b[0;32m    982\u001b[0m             \u001b[0merror_class\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexceptions\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfrom_code\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0merror_code\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 983\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0merror_class\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mparsed_response\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0moperation_name\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    984\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    985\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0mparsed_response\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mClientError\u001b[0m: An error occurred (ValidationException) when calling the CreateEndpointConfig operation: Cannot create already existing endpoint configuration \"arn:aws:sagemaker:us-east-1:728939754004:endpoint-config/simple-linear-regression-endpoint\"."
     ]
    }
   ],
   "source": [
    "# Deploy the model to an endpoint\n",
    "predictor = model.deploy(\n",
    "    initial_instance_count=1,\n",
    "    instance_type='ml.m5.large',\n",
    "    endpoint_name=endpoint_name\n",
    ")\n",
    "\n",
    "print(f\"Endpoint {endpoint_name} created successfully.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "sagemaker.config INFO - Not applying SDK defaults from location: C:\\ProgramData\\sagemaker\\sagemaker\\config.yaml\n",
      "sagemaker.config INFO - Not applying SDK defaults from location: C:\\Users\\Admin\\AppData\\Local\\sagemaker\\sagemaker\\config.yaml\n",
      "Endpoint configuration simple-linear-regression-endpoint-config does not exist. Proceeding to create a new one.\n",
      "Endpoint configuration simple-linear-regression-endpoint-config has been deleted.\n",
      "Endpoint simple-linear-regression-endpoint does not exist. Proceeding to create a new one.\n"
     ]
    }
   ],
   "source": [
    "# Install necessary libraries\n",
    "# !pip install boto3 sagemaker pandas scikit-learn\n",
    "\n",
    "# Import necessary libraries\n",
    "import boto3\n",
    "import sagemaker\n",
    "from sagemaker import get_execution_role\n",
    "import time\n",
    "\n",
    "# Define parameters\n",
    "role = 'arn:aws:iam::728939754004:role/service-role/AmazonSageMaker-ExecutionRole-20230821T133341'  # Your SageMaker execution role ARN\n",
    "region = 'us-east-1'\n",
    "s3_bucket = 'justin-inferences'  # Your S3 bucket for model artifacts\n",
    "model_artifact_path = f's3://{s3_bucket}/model/model.pkl'\n",
    "endpoint_name = 'simple-linear-regression-endpoint'\n",
    "endpoint_config_name = 'simple-linear-regression-endpoint-config'\n",
    "\n",
    "# Create a SageMaker session\n",
    "sagemaker_session = sagemaker.Session()\n",
    "\n",
    "# Initialize SageMaker client\n",
    "sm_client = boto3.client('sagemaker', region_name=region)\n",
    "\n",
    "# Function to delete existing endpoint configuration\n",
    "def delete_endpoint_config(config_name):\n",
    "    try:\n",
    "        sm_client.describe_endpoint_config(EndpointConfigName=config_name)\n",
    "        print(f\"Endpoint configuration {config_name} already exists. Deleting it...\")\n",
    "        sm_client.delete_endpoint_config(EndpointConfigName=config_name)\n",
    "        print(f\"Deleted endpoint configuration {config_name}.\")\n",
    "    except sm_client.exceptions.ClientError as e:\n",
    "        if 'ValidationException' in str(e):\n",
    "            print(f\"Endpoint configuration {config_name} does not exist. Proceeding to create a new one.\")\n",
    "        else:\n",
    "            raise e\n",
    "\n",
    "# Function to delete existing endpoint\n",
    "def delete_endpoint(endpoint_name):\n",
    "    try:\n",
    "        sm_client.describe_endpoint(EndpointName=endpoint_name)\n",
    "        print(f\"Endpoint {endpoint_name} already exists. Deleting it...\")\n",
    "        sm_client.delete_endpoint(EndpointName=endpoint_name)\n",
    "        print(f\"Deleted endpoint {endpoint_name}.\")\n",
    "        # Wait for the endpoint to be deleted\n",
    "        waiter = sm_client.get_waiter('endpoint_deleted')\n",
    "        waiter.wait(EndpointName=endpoint_name)\n",
    "        print(f\"Endpoint {endpoint_name} deleted.\")\n",
    "    except sm_client.exceptions.ClientError as e:\n",
    "        if 'ValidationException' in str(e):\n",
    "            print(f\"Endpoint {endpoint_name} does not exist. Proceeding to create a new one.\")\n",
    "        else:\n",
    "            raise e\n",
    "\n",
    "# Delete existing endpoint configuration if it exists\n",
    "delete_endpoint_config(endpoint_config_name)\n",
    "\n",
    "# Ensure endpoint configuration is deleted before proceeding\n",
    "while True:\n",
    "    try:\n",
    "        sm_client.describe_endpoint_config(EndpointConfigName=endpoint_config_name)\n",
    "        print(f\"Waiting for endpoint configuration {endpoint_config_name} to be deleted...\")\n",
    "        time.sleep(10)\n",
    "    except sm_client.exceptions.ClientError as e:\n",
    "        if 'ValidationException' in str(e):\n",
    "            print(f\"Endpoint configuration {endpoint_config_name} has been deleted.\")\n",
    "            break\n",
    "        else:\n",
    "            raise e\n",
    "\n",
    "# Delete existing endpoint if it exists\n",
    "delete_endpoint(endpoint_name)\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "sagemaker.config INFO - Not applying SDK defaults from location: C:\\ProgramData\\sagemaker\\sagemaker\\config.yaml\n",
      "sagemaker.config INFO - Not applying SDK defaults from location: C:\\Users\\Admin\\AppData\\Local\\sagemaker\\sagemaker\\config.yaml\n",
      "Endpoint configuration simple-linear-regression-endpoint-config does not exist. Proceeding to create a new one.\n",
      "Endpoint simple-linear-regression-endpoint does not exist. Creating it...\n"
     ]
    },
    {
     "ename": "ClientError",
     "evalue": "An error occurred (ValidationException) when calling the CreateEndpointConfig operation: Cannot create already existing endpoint configuration \"arn:aws:sagemaker:us-east-1:728939754004:endpoint-config/simple-linear-regression-endpoint\".",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mClientError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_39316/2603940278.py\u001b[0m in \u001b[0;36mcreate_or_update_endpoint\u001b[1;34m(model, endpoint_name)\u001b[0m\n\u001b[0;32m     41\u001b[0m         \u001b[1;31m# Try to describe the endpoint\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 42\u001b[1;33m         \u001b[0mresponse\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0msm_client\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdescribe_endpoint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mEndpointName\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mendpoint_name\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     43\u001b[0m         \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34mf\"Endpoint {endpoint_name} already exists. Updating it...\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\Admin\\anaconda3\\envs\\tf-gpu-cuda8\\lib\\site-packages\\botocore\\client.py\u001b[0m in \u001b[0;36m_api_call\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    534\u001b[0m             \u001b[1;31m# The \"self\" in this scope is referring to the BaseClient.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 535\u001b[1;33m             \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_make_api_call\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0moperation_name\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    536\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\Admin\\anaconda3\\envs\\tf-gpu-cuda8\\lib\\site-packages\\botocore\\client.py\u001b[0m in \u001b[0;36m_make_api_call\u001b[1;34m(self, operation_name, api_params)\u001b[0m\n\u001b[0;32m    982\u001b[0m             \u001b[0merror_class\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexceptions\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfrom_code\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0merror_code\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 983\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0merror_class\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mparsed_response\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0moperation_name\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    984\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mClientError\u001b[0m: An error occurred (ValidationException) when calling the DescribeEndpoint operation: Could not find endpoint \"simple-linear-regression-endpoint\".",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mClientError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_39316/2603940278.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     76\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     77\u001b[0m \u001b[1;31m# Create or update the endpoint\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 78\u001b[1;33m \u001b[0mcreate_or_update_endpoint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmodel\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mendpoint_name\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_39316/2603940278.py\u001b[0m in \u001b[0;36mcreate_or_update_endpoint\u001b[1;34m(model, endpoint_name)\u001b[0m\n\u001b[0;32m     55\u001b[0m             \u001b[1;31m# If the endpoint does not exist, create it\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     56\u001b[0m             \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34mf\"Endpoint {endpoint_name} does not exist. Creating it...\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 57\u001b[1;33m             model.deploy(\n\u001b[0m\u001b[0;32m     58\u001b[0m                 \u001b[0minitial_instance_count\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     59\u001b[0m                 \u001b[0minstance_type\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0minstance_type\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\Admin\\anaconda3\\envs\\tf-gpu-cuda8\\lib\\site-packages\\sagemaker\\model.py\u001b[0m in \u001b[0;36mdeploy\u001b[1;34m(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, tags, kms_key, wait, data_capture_config, async_inference_config, serverless_inference_config, volume_size, model_data_download_timeout, container_startup_health_check_timeout, inference_recommendation_id, explainer_config, accept_eula, **kwargs)\u001b[0m\n\u001b[0;32m   1503\u001b[0m             \u001b[0mexplainer_config_dict\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mexplainer_config\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_to_request_dict\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1504\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1505\u001b[1;33m         self.sagemaker_session.endpoint_from_production_variants(\n\u001b[0m\u001b[0;32m   1506\u001b[0m             \u001b[0mname\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mendpoint_name\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1507\u001b[0m             \u001b[0mproduction_variants\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mproduction_variant\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\Admin\\anaconda3\\envs\\tf-gpu-cuda8\\lib\\site-packages\\sagemaker\\session.py\u001b[0m in \u001b[0;36mendpoint_from_production_variants\u001b[1;34m(self, name, production_variants, tags, kms_key, wait, data_capture_config_dict, async_inference_config_dict, explainer_config_dict)\u001b[0m\n\u001b[0;32m   4847\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   4848\u001b[0m         \u001b[0mLOGGER\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0minfo\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Creating endpoint-config with name %s\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mname\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 4849\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msagemaker_client\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcreate_endpoint_config\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m**\u001b[0m\u001b[0mconfig_options\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   4850\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   4851\u001b[0m         return self.create_endpoint(\n",
      "\u001b[1;32mc:\\Users\\Admin\\anaconda3\\envs\\tf-gpu-cuda8\\lib\\site-packages\\botocore\\client.py\u001b[0m in \u001b[0;36m_api_call\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    533\u001b[0m                 )\n\u001b[0;32m    534\u001b[0m             \u001b[1;31m# The \"self\" in this scope is referring to the BaseClient.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 535\u001b[1;33m             \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_make_api_call\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0moperation_name\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    536\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    537\u001b[0m         \u001b[0m_api_call\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__name__\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mstr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpy_operation_name\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\Users\\Admin\\anaconda3\\envs\\tf-gpu-cuda8\\lib\\site-packages\\botocore\\client.py\u001b[0m in \u001b[0;36m_make_api_call\u001b[1;34m(self, operation_name, api_params)\u001b[0m\n\u001b[0;32m    981\u001b[0m             )\n\u001b[0;32m    982\u001b[0m             \u001b[0merror_class\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexceptions\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfrom_code\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0merror_code\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 983\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0merror_class\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mparsed_response\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0moperation_name\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    984\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    985\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0mparsed_response\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mClientError\u001b[0m: An error occurred (ValidationException) when calling the CreateEndpointConfig operation: Cannot create already existing endpoint configuration \"arn:aws:sagemaker:us-east-1:728939754004:endpoint-config/simple-linear-regression-endpoint\"."
     ]
    }
   ],
   "source": [
    "# Install necessary libraries\n",
    "# !pip install boto3 sagemaker pandas scikit-learn\n",
    "\n",
    "# Import necessary libraries\n",
    "import boto3\n",
    "import sagemaker\n",
    "from sagemaker import get_execution_role\n",
    "from sagemaker.predictor import Predictor\n",
    "\n",
    "# Define parameters\n",
    "role = 'arn:aws:iam::728939754004:role/service-role/AmazonSageMaker-ExecutionRole-20230821T133341'  # Your SageMaker execution role ARN\n",
    "region = 'us-east-1'\n",
    "s3_bucket = 'justin-inferences'  # Your S3 bucket for model artifacts\n",
    "model_artifact_path = f's3://{s3_bucket}/model/model.pkl'\n",
    "endpoint_name = 'simple-linear-regression-endpoint'\n",
    "instance_type = 'ml.m5.large'\n",
    "endpoint_config_name = 'simple-linear-regression-endpoint-config'\n",
    "\n",
    "# Create a SageMaker session\n",
    "sagemaker_session = sagemaker.Session()\n",
    "\n",
    "# Initialize SageMaker client\n",
    "sm_client = boto3.client('sagemaker', region_name=region)\n",
    "\n",
    "# Function to delete existing endpoint configuration\n",
    "def delete_endpoint_config(config_name):\n",
    "    try:\n",
    "        sm_client.describe_endpoint_config(EndpointConfigName=config_name)\n",
    "        print(f\"Endpoint configuration {config_name} already exists. Deleting it...\")\n",
    "        sm_client.delete_endpoint_config(EndpointConfigName=config_name)\n",
    "        print(f\"Deleted endpoint configuration {config_name}.\")\n",
    "    except sm_client.exceptions.ClientError as e:\n",
    "        if e.response['Error']['Code'] == 'ValidationException':\n",
    "            print(f\"Endpoint configuration {config_name} does not exist. Proceeding to create a new one.\")\n",
    "        else:\n",
    "            raise e\n",
    "\n",
    "# Function to create or update an endpoint\n",
    "def create_or_update_endpoint(model, endpoint_name):\n",
    "    try:\n",
    "        # Try to describe the endpoint\n",
    "        response = sm_client.describe_endpoint(EndpointName=endpoint_name)\n",
    "        print(f\"Endpoint {endpoint_name} already exists. Updating it...\")\n",
    "        \n",
    "        # Update the endpoint with a new model\n",
    "        model.deploy(\n",
    "            initial_instance_count=1,\n",
    "            instance_type=instance_type,\n",
    "            endpoint_name=endpoint_name,\n",
    "            update_endpoint=True\n",
    "        )\n",
    "        print(f\"Endpoint {endpoint_name} updated successfully.\")\n",
    "    except sm_client.exceptions.ClientError as e:\n",
    "        if e.response['Error']['Code'] == 'ValidationException':\n",
    "            # If the endpoint does not exist, create it\n",
    "            print(f\"Endpoint {endpoint_name} does not exist. Creating it...\")\n",
    "            model.deploy(\n",
    "                initial_instance_count=1,\n",
    "                instance_type=instance_type,\n",
    "                endpoint_name=endpoint_name\n",
    "            )\n",
    "            print(f\"Endpoint {endpoint_name} created successfully.\")\n",
    "        else:\n",
    "            print(f\"Failed to create or update endpoint {endpoint_name}: {str(e)}\")\n",
    "\n",
    "# Delete existing endpoint configuration if it exists\n",
    "delete_endpoint_config(endpoint_config_name)\n",
    "\n",
    "# Create a SageMaker model\n",
    "model = sagemaker.model.Model(\n",
    "    model_data=model_artifact_path,\n",
    "    image_uri=sagemaker.image_uris.retrieve('linear-learner', region),\n",
    "    role=role,\n",
    "    sagemaker_session=sagemaker_session\n",
    ")\n",
    "\n",
    "# Create or update the endpoint\n",
    "create_or_update_endpoint(model, endpoint_name)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.8.12 ('tf-gpu-cuda8')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "7fe8e7156b155a9f3c09b83080291bb1bd38144b8399c123115114f3487f3b24"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
